services:
  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    environment:
      PUID: 1000
      PGID: 1000
      FLATNOTES_AUTH_TYPE: "password"
      FLATNOTES_USERNAME: soconnor16
      FLATNOTES_PASSWORD: ${PSWD}
      FLATNOTES_SECRET_KEY: ${SECRET_KEY}
    volumes:
      - /srv/services/flatnotes/data:/data
    ports:
      - "8002:8080"
    restart: unless-stopped
